### ISSUE TITLE
Non-Standard C

### ISSUE THREAD

**Issue by resyfer** [ComputerScienceSoceityNITS/Stack-in-C-24#6]
**Describe the bug**
[This issue](https://github.com/Raj217/Stack-in-C/issues/5). Since this repo is ahead of upstream, I'm guessing the original one won't really be "maintained".

**Comment by resyfer** [comment]
@Mastermind-sap

**Comment by Mastermind-sap** [comment]
Well, actually this fork is also not really maintained. It is ahead of the upstream as there had been some templates added for the Open Source Marathon organized by CSS. There are not really any code changes. I will let the original maintainer know about the issue. @resyfer
